### PR TITLE
Fix: HTTPD_ERRORLOG should match when module missing

### LINKED ISSUE #259: HTTPD24_ERRORLOG fails if module not present
**Issue description**

For Apache 2.4 error logs, if the module string is empty, the HTTPD24_ERRORLOG grok pattern fails (`_grokparsefailure`).

Example log entry:
`[Tue Apr 14 14:27:52.605084 2020] [:error] [pid 5688] [client XX.XX.XX.XX:8196] script '/XXX/wp-login.php' not found or unable to stat`

**Workaround**

Expand `%{HTTPD24_ERRORLOG}` and replace this part:

`\[%{WORD:module}:%{LOGLEVEL:loglevel}\]`

with this:

`\[(%{WORD:module})?:%{LOGLEVEL:loglevel}\]`

**Details for fast resolution**

- Version: 7.6.1
- Operating System: docker on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by kares**
fixes #259

### CODE REVIEW

File: spec/patterns/httpd_spec.rb [hunk 1]
```diff
@@ -262,6 +262,24 @@
...
+    let(:message) do
+      "[Tue Apr 14 14:27:52.605084 2020] [:error] [pid 5688] [client 192.168.10.110:8196] script '/login/wp-login.php' not found or unable to stat"
+    end
+
+    it "matches" do
+      expect(grok).to include('timestamp' => 'Tue Apr 14 14:27:52.605084 2020')
+      if ecs_compatibility?
+        expect(grok).to include("log"=>{"level" => "error"})
+        expect(grok).to include("process"=>{"pid" => 5688})
+        expect(grok).to include("process"=>{"pid" => 5688})
```
Comment (yaauie) [inline spec/patterns/httpd_spec.rb:275]: dup of line above

```suggestion
```

**Review by yaauie — APPROVED** [review]
left one nit of a duplicated expectation in spec, otherwise LGTM
